# copied from
# https://github.com/magnars/s.el/blob/dda84d38fffdaf0c9b12837b504b402af910d01d/.github/workflows/test.yml
name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 29.1
          - 29.2
          - 29.3
          - 29.4
          - snapshot
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Emacs
      uses: purcell/setup-emacs@v4.0
      with:
        version: ${{ matrix.emacs_version }}

    - name: Test
      run: |
        ./ci.sh
